#!/bin/bash

set -e

DATE="$1"
MAIN_DIR="$(pwd)"
SNAPSHOTS_DIR=$MAIN_DIR/snapshots
TIME_LAPSE_PATH="$MAIN_DIR/time-lapse-$DATE.mp4"

echo "Creating time-lapse for snapshots matching $DATE"

sleep 2
rm -f $TIME_LAPSE_PATH

cat $SNAPSHOTS_DIR/$DATE*.jpg | ffmpeg -r 10 -i - -c:v libx264 -vf "format=yuv420p,scale=1280:-2" $TIME_LAPSE_PATH
