#!/bin/bash

set -e

DATE="$1"
MAIN_DIR=(pwd)
SNAPSHOTS_DIR=$MAIN_DIR/snapshots
TIMELAPSE_PATH="$MAIN_DIR/timelapse-$DATE.mp4"

echo "Creating timelapse for snapshots matching $DATE"

sleep 2

cat $SNAPSHOTS_DIR/$DATE*.jpg | ffmpeg -r 10 -i - -vf format=yuv420p -vf scale=1280:-2 $TIMELAPSE_PATH