#!/bin/bash

set -e

MAIN_DIR="$(pwd)"
FPS=${1:-30}
SNAPSHOTS_DIR=$MAIN_DIR/snapshots
TIMELAPSES_DIR=$MAIN_DIR/timelapses
TIME_LAPSE_PATH="$TIMELAPSES_DIR/time-lapse-all-$FPS-fps.mp4"

echo "Creating time-lapse for snapshots matching in $FPS fps"
mkdir -p $TIMELAPSES_DIR
sleep 2
rm -f $TIME_LAPSE_PATH

cat $SNAPSHOTS_DIR/*.jpg | ffmpeg -r $FPS -i - -c:v libx264 -vf "format=yuv420p,scale=3280:-2" $TIME_LAPSE_PATH

echo "Successfully created $TIME_LAPSE_PATH"
