#!/bin/bash

set -e

DATE=$(date -u +"%Y-%m-%d")
MAIN_DIR="$(pwd)"
SNAPSHOTS_DIR=$MAIN_DIR/snapshots
TIMELAPSES_DIR=$MAIN_DIR/timelapses

function create () {
  DATE=$1
  FPS=$2
  TIME_LAPSE_PATH="$TIMELAPSES_DIR/time-lapse-$DATE-$FPS-fps.mp4"
  echo "Creating time-lapse for snapshots matching $DATE in $FPS fps"

  rm -f $TIME_LAPSE_PATH

  cat $SNAPSHOTS_DIR/$DATE*.jpg | ffmpeg -r $FPS -i - -c:v libx264 -vf "format=yuv420p,scale=1280:-2" $TIME_LAPSE_PATH

  echo "Successfully created $TIME_LAPSE_PATH"
}

time create $DATE 15
time create $DATE 20
time create $DATE 30
time create $DATE 60


